apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: pingpong
          image: pingpong:1.11
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: shared-storage
              mountPath: /usr/src/app/files
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 128Mi