apiVersion: v1
kind: Service
metadata:
  name: todo-postgres-svc
  namespace: project
  labels:
    app: todo-postgres
spec:
  clusterIP: None
  ports:
    - port: 5432
      name: postgres
  selector:
    app: todo-postgres