apiVersion: batch/v1
kind: CronJob
metadata:
  name: todo-random-reminder
  namespace: project
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: todo-cronjob
              image: todo-cronjob:2.9
              imagePullPolicy: IfNotPresent
              envFrom:
                - configMapRef:
                    name: todo-cronjob-config
              resources:
                requests:
                  cpu: 10m
                  memory: 16Mi
                limits:
                  cpu: 100m
                  memory: 128Mi