apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-status        # emptyDir, writer<->reader (from 1.10)
          emptyDir: {}
      containers:
        - name: writer
          image: log-output-writer:1.10
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/files
        - name: reader
          image: log-output-reader:2.1
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - name: shared-status
              mountPath: /usr/src/app/files