apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: project
data:
  PORT: "3000"
  BACKEND_URL: "http://todo-backend-svc:2345/todos"
  IMAGE_URL: "https://picsum.photos/1200"
  CACHE_MINUTES: "10"